/**
 * FANZ Ecosystem Registry
 * Master configuration for all platforms, services, and AI bots
 *
 * STATUS GUIDE:
 * - 'active': Fully operational, audited, ready for use
 * - 'pending_audit': Deployed but needs full crawl/audit before activation
 * - 'coming_soon': In development, not yet deployed
 * - 'maintenance': Temporarily offline for maintenance
 */

export type PlatformStatus = 'active' | 'pending_audit' | 'coming_soon' | 'maintenance';
export type PlatformCategory = 'fan_platform' | 'infrastructure' | 'auxiliary' | 'ai_bot' | 'support';

export interface FanzPlatform {
  id: string;
  name: string;
  slug: string;
  domain: string;
  port: number;
  logoUrl: string;
  primaryColor: string;
  secondaryColor: string;
  accentColor: string;
  backgroundColor: string;
  description: string;
  tagline?: string;
  category: PlatformCategory;
  status: PlatformStatus;
  isUserFacing: boolean;
  requiresAuth: boolean;
  ssoEnabled: boolean;
  platformId: string;
  dbName: string;
  features?: string[];
  lastAuditDate?: string;
  auditNotes?: string;
}

// ============================================
// FAN PLATFORMS (16 Active Content Platforms)
// ============================================
export const FAN_PLATFORMS: FanzPlatform[] = [
  {
    id: 'boyfanz',
    name: 'BoyFanz',
    slug: 'boyfanz',
    domain: 'boy.fanz.website',
    port: 3003,
    logoUrl: '/platforms/boyfanz-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#ffffff',
    backgroundColor: '#0a0a0a',
    description: 'Premium male content creators',
    tagline: "Every Man's Playground",
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'boyfanz',
    dbName: 'boyfanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'girlfanz',
    name: 'GirlFanz',
    slug: 'girlfanz',
    domain: 'girl.fanz.website',
    port: 3001,
    logoUrl: '/platforms/girlfanz-logo.png',
    primaryColor: '#ff69b4',
    secondaryColor: '#9c4eb4',
    accentColor: '#5bcefa',
    backgroundColor: '#0a0a0a',
    description: 'Premium female content creators',
    tagline: 'Empowered Expression',
    category: 'fan_platform',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'girlfanz',
    dbName: 'girlfanz_db',
    auditNotes: 'Needs full page crawl and env configuration',
  },
  {
    id: 'gayfanz',
    name: 'GayFanz',
    slug: 'gayfanz',
    domain: 'gay.fanz.website',
    port: 3014,
    logoUrl: '/platforms/gayfanz-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#000000',
    description: 'LGBTQ+ male creators',
    tagline: 'Underground Fight Ring',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'gayfanz',
    dbName: 'gayfanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'transfanz',
    name: 'TransFanz',
    slug: 'transfanz',
    domain: 'trans.fanz.website',
    port: 3007,
    logoUrl: '/platforms/transfanz-logo.png',
    primaryColor: '#F5A9B8',
    secondaryColor: '#5BCEFA',
    accentColor: '#9c4eb4',
    backgroundColor: '#0a0a14',
    description: 'Trans & non-binary creators',
    tagline: 'Embrace Your True Self',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'transfanz',
    dbName: 'transfanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'milffanz',
    name: 'MilfFanz',
    slug: 'milffanz',
    domain: 'milf.fanz.website',
    port: 3017,
    logoUrl: '/platforms/milffanz-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#000000',
    description: 'Mature women creators',
    tagline: 'Experience Matters',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'milffanz',
    dbName: 'milffanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'cougarfanz',
    name: 'CougarFanz',
    slug: 'cougarfanz',
    domain: 'cougar.fanz.website',
    port: 3003,
    logoUrl: '/platforms/cougarfanz-logo.png',
    primaryColor: '#D4AF37',
    secondaryColor: '#722F37',
    accentColor: '#B8860B',
    backgroundColor: '#1a1a1a',
    description: 'Sophisticated mature creators',
    tagline: 'Where Experience is Worshipped',
    category: 'fan_platform',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'cougarfanz',
    dbName: 'cougarfanz_db',
    auditNotes: 'DB errors in marketing service',
  },
  {
    id: 'bearfanz',
    name: 'BearFanz',
    slug: 'bearfanz',
    domain: 'bear.fanz.website',
    port: 3005,
    logoUrl: '/platforms/bearfanz-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#050505',
    description: 'Bear community creators',
    tagline: 'Bear Den',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'bearfanz',
    dbName: 'bearfanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'daddyfanz',
    name: 'DaddyFanz',
    slug: 'daddyfanz',
    domain: 'daddy.fanz.website',
    port: 3011,
    logoUrl: '/platforms/daddyfanz-logo.png',
    primaryColor: '#00CFFF',
    secondaryColor: '#F5C237',
    accentColor: '#7B8794',
    backgroundColor: '#0a0a0a',
    description: 'Mature masculine creators',
    tagline: 'The Dungeon',
    category: 'fan_platform',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'daddyfanz',
    dbName: 'daddyfanz_db',
    auditNotes: 'Missing OPENAI_API_KEY, high memory usage',
  },
  {
    id: 'pupfanz',
    name: 'PupFanz',
    slug: 'pupfanz',
    domain: 'pup.fanz.website',
    port: 3006,
    logoUrl: '/platforms/pupfanz-logo.png',
    primaryColor: '#ff8c00',
    secondaryColor: '#4169e1',
    accentColor: '#ffffff',
    backgroundColor: '#fff8f0',
    description: 'Pup play community',
    tagline: 'Community Playground',
    category: 'fan_platform',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'pupfanz',
    dbName: 'pupfanz_db',
    auditNotes: 'High restart count (90+)',
  },
  {
    id: 'taboofanz',
    name: 'TabooFanz',
    slug: 'taboofanz',
    domain: 'taboo.fanz.website',
    port: 3019,
    logoUrl: '/platforms/taboofanz-logo.png',
    primaryColor: '#ff00ff',
    secondaryColor: '#00ffff',
    accentColor: '#00ffff',
    backgroundColor: '#0a0a0f',
    description: 'Edge content creators',
    tagline: 'Beyond Boundaries',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'taboofanz',
    dbName: 'taboofanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzuncut',
    name: 'FanzUncut',
    slug: 'fanzuncut',
    domain: 'uncut.fanz.website',
    port: 3020,
    logoUrl: '/platforms/fanzuncut-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#050505',
    description: 'Uncensored content',
    tagline: 'Raw & Unfiltered',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'fanzuncut',
    dbName: 'fanzuncut_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'femmefanz',
    name: 'FemmeFanz',
    slug: 'femmefanz',
    domain: 'femme.fanz.website',
    port: 3013,
    logoUrl: '/platforms/femmefanz-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#000000',
    description: 'Feminine creators showcase',
    tagline: 'Feminine Power',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'femmefanz',
    dbName: 'femmefanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'brofanz',
    name: 'BroFanz',
    slug: 'brofanz',
    domain: 'bro.fanz.website',
    port: 3022,
    logoUrl: '/platforms/brofanz-logo.png',
    primaryColor: '#1E90FF',
    secondaryColor: '#7FFF00',
    accentColor: '#00FFFF',
    backgroundColor: '#0a0a0f',
    description: 'Athletic creators',
    tagline: 'The Brotherhood Network',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'brofanz',
    dbName: 'brofanz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'southernfanz',
    name: 'SouthernFanz',
    slug: 'southernfanz',
    domain: 'southern.fanz.website',
    port: 3215,
    logoUrl: '/platforms/southernfanz-logo.png',
    primaryColor: '#D4A000',
    secondaryColor: '#8B4513',
    accentColor: '#D4A000',
    backgroundColor: '#0f0a06',
    description: 'Country & southern creators',
    tagline: 'Country. Unfiltered. Creator-owned.',
    category: 'fan_platform',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'southernfanz',
    dbName: 'southernfanz_db',
    auditNotes: 'Has advanced infra config, needs page audit',
  },
  {
    id: 'dlbroz',
    name: 'DLBroz',
    slug: 'dlbroz',
    domain: 'dlbroz.fanz.website',
    port: 3015,
    logoUrl: '/platforms/dlbroz-logo.png',
    primaryColor: '#334155',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#000000',
    description: 'Discreet masculine space',
    tagline: 'On The Down Low',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'dlbroz',
    dbName: 'dlbroz_db',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'guyz',
    name: 'Guyz',
    slug: 'guyz',
    domain: 'guyz.fanz.website',
    port: 3016,
    logoUrl: '/platforms/guyz-logo.png',
    primaryColor: '#ff0000',
    secondaryColor: '#d4af37',
    accentColor: '#d4af37',
    backgroundColor: '#000000',
    description: 'General male creators',
    tagline: 'For The Guys',
    category: 'fan_platform',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'guyz',
    dbName: 'guyz_db',
    lastAuditDate: '2025-12-28',
  },
];

// ============================================
// INFRASTRUCTURE SERVICES
// ============================================
export const INFRASTRUCTURE_SERVICES: FanzPlatform[] = [
  {
    id: 'fanzdash',
    name: 'FanzDash',
    slug: 'fanzdash',
    domain: 'dash.fanz.website',
    port: 3000,
    logoUrl: '/platforms/fanzdash-logo.png',
    primaryColor: '#8b5cf6',
    secondaryColor: '#6366f1',
    accentColor: '#a855f7',
    backgroundColor: '#0f0f23',
    description: 'Central Command Center',
    tagline: 'Control Everything',
    category: 'infrastructure',
    status: 'active',
    isUserFacing: true,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanzdash',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzsso',
    name: 'FanzSSO',
    slug: 'fanzsso',
    domain: 'sso.fanz.website',
    port: 3100,
    logoUrl: '/platforms/fanzsso-logo.png',
    primaryColor: '#10b981',
    secondaryColor: '#059669',
    accentColor: '#34d399',
    backgroundColor: '#0f172a',
    description: 'Single Sign-On Portal',
    tagline: 'One Login, All Platforms',
    category: 'infrastructure',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: false,
    platformId: 'fanzsso',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzpay',
    name: 'FanzPay',
    slug: 'fanzpay',
    domain: 'pay.fanz.website',
    port: 3051,
    logoUrl: '/platforms/fanzpay-logo.png',
    primaryColor: '#fbbf24',
    secondaryColor: '#f59e0b',
    accentColor: '#fcd34d',
    backgroundColor: '#1c1917',
    description: 'Payment Processing',
    tagline: 'Secure Creator Payments',
    category: 'infrastructure',
    status: 'active',
    isUserFacing: false,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanzpay',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzmediahub',
    name: 'FanzMediaHub',
    slug: 'fanzmediahub',
    domain: 'media.fanz.website',
    port: 3056,
    logoUrl: '/platforms/mediahub-logo.png',
    primaryColor: '#ef4444',
    secondaryColor: '#dc2626',
    accentColor: '#f87171',
    backgroundColor: '#18181b',
    description: 'Media Processing & CDN',
    tagline: 'Lightning Fast Media',
    category: 'infrastructure',
    status: 'active',
    isUserFacing: false,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanzmediahub',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzvault',
    name: 'FanzVault',
    slug: 'fanzvault',
    domain: 'vault.fanz.website',
    port: 3030,
    logoUrl: '/platforms/vault-logo.png',
    primaryColor: '#0ea5e9',
    secondaryColor: '#0284c7',
    accentColor: '#38bdf8',
    backgroundColor: '#0c0a09',
    description: 'Encrypted Document Storage',
    tagline: 'Your Secrets, Protected',
    category: 'infrastructure',
    status: 'active',
    isUserFacing: false,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanzvault',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
];

// ============================================
// AUXILIARY SERVICES (User-Facing)
// ============================================
export const AUXILIARY_SERVICES: FanzPlatform[] = [
  {
    id: 'fanzknowledgebase',
    name: 'Knowledge Base',
    slug: 'kb',
    domain: 'kb.fanz.website',
    port: 3060,
    logoUrl: '/platforms/kb-logo.png',
    primaryColor: '#3b82f6',
    secondaryColor: '#2563eb',
    accentColor: '#60a5fa',
    backgroundColor: '#0f172a',
    description: 'Help & Documentation',
    tagline: 'Find Answers Fast',
    category: 'auxiliary',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'knowledge-base',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzhub',
    name: 'FanzHub',
    slug: 'fanzhub',
    domain: 'hub.fanz.website',
    port: 3080,
    logoUrl: '/platforms/hub-logo.png',
    primaryColor: '#f97316',
    secondaryColor: '#ea580c',
    accentColor: '#fb923c',
    backgroundColor: '#1c1917',
    description: 'Creator Hub & Community',
    tagline: 'Connect With Creators',
    category: 'auxiliary',
    status: 'active',
    isUserFacing: true,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'hubfanz',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzroulette',
    name: 'FanzRoulette',
    slug: 'roulette',
    domain: 'roulette.fanz.website',
    port: 3125,
    logoUrl: '/platforms/roulette-logo.png',
    primaryColor: '#ec4899',
    secondaryColor: '#db2777',
    accentColor: '#f472b6',
    backgroundColor: '#0a0a0a',
    description: 'Random Creator Discovery',
    tagline: 'Spin The Wheel',
    category: 'auxiliary',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: true,
    platformId: 'fanz-roulette',
    dbName: 'fanz_core',
    auditNotes: 'Has high restart count',
  },
  {
    id: 'fanzmobile',
    name: 'FanzMobile',
    slug: 'fanzmobile',
    domain: 'mobile.fanz.website',
    port: 3101,
    logoUrl: '/platforms/mobile-logo.png',
    primaryColor: '#22c55e',
    secondaryColor: '#16a34a',
    accentColor: '#4ade80',
    backgroundColor: '#0f172a',
    description: 'Mobile App Backend',
    tagline: 'Fanz On The Go',
    category: 'auxiliary',
    status: 'active',
    isUserFacing: true,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanzmobile',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzincognito',
    name: 'FanzIncognito',
    slug: 'incognito',
    domain: 'incognito.fanz.website',
    port: 3058,
    logoUrl: '/platforms/incognito-logo.png',
    primaryColor: '#1e1b4b',
    secondaryColor: '#312e81',
    accentColor: '#4f46e5',
    backgroundColor: '#020617',
    description: 'Private Browsing Mode',
    tagline: 'Browse Anonymously',
    category: 'auxiliary',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: false,
    platformId: 'fanz-incognito',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
];

// ============================================
// AI BOTS & USER-FACING AI SERVICES
// ============================================
export const AI_SERVICES: FanzPlatform[] = [
  {
    id: 'fanzgpt',
    name: 'FanzGPT',
    slug: 'gpt',
    domain: 'gpt.fanz.website',
    port: 3110,
    logoUrl: '/platforms/gpt-logo.png',
    primaryColor: '#00d4ff',
    secondaryColor: '#0891b2',
    accentColor: '#22d3ee',
    backgroundColor: '#0f172a',
    description: 'AI Chat Assistant',
    tagline: 'Your AI Companion',
    category: 'ai_bot',
    status: 'pending_audit',
    isUserFacing: true,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'gpt-fanz',
    dbName: 'fanz_core',
    auditNotes: 'High restart count (7)',
  },
  {
    id: 'fanzai',
    name: 'FanzAI Studio',
    slug: 'ai',
    domain: 'ai.fanz.website',
    port: 3105,
    logoUrl: '/platforms/ai-logo.png',
    primaryColor: '#a855f7',
    secondaryColor: '#9333ea',
    accentColor: '#c084fc',
    backgroundColor: '#0a0a0a',
    description: 'AI Content Tools',
    tagline: 'Create With AI',
    category: 'ai_bot',
    status: 'active',
    isUserFacing: true,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'ai-fanz',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzbot',
    name: 'FanzBot',
    slug: 'bot',
    domain: 'bot.fanz.website',
    port: 3081,
    logoUrl: '/platforms/bot-logo.png',
    primaryColor: '#06b6d4',
    secondaryColor: '#0891b2',
    accentColor: '#22d3ee',
    backgroundColor: '#18181b',
    description: 'Automated Assistant',
    tagline: 'Smart Automation',
    category: 'ai_bot',
    status: 'active',
    isUserFacing: true,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanz-bot',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'ceobot',
    name: 'CEO Bot',
    slug: 'ceo',
    domain: 'ceo.fanz.website',
    port: 3043,
    logoUrl: '/platforms/ceo-logo.png',
    primaryColor: '#fbbf24',
    secondaryColor: '#d97706',
    accentColor: '#fcd34d',
    backgroundColor: '#1c1917',
    description: 'Executive AI Assistant',
    tagline: 'AI-Powered Decisions',
    category: 'ai_bot',
    status: 'active',
    isUserFacing: false,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'ceo-fanz',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
];

// ============================================
// SUPPORT & RECOVERY
// ============================================
export const SUPPORT_SERVICES: FanzPlatform[] = [
  {
    id: 'recoveryfanz',
    name: 'RecoveryFanz',
    slug: 'recovery',
    domain: 'recoveryfanz.com',
    port: 0,
    logoUrl: '/platforms/recovery-logo.png',
    primaryColor: '#10b981',
    secondaryColor: '#059669',
    accentColor: '#34d399',
    backgroundColor: '#0f172a',
    description: 'Account Recovery & Support',
    tagline: 'Get Back On Track',
    category: 'support',
    status: 'active',
    isUserFacing: true,
    requiresAuth: false,
    ssoEnabled: false,
    platformId: 'recoveryfanz',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
  {
    id: 'fanzmod',
    name: 'FanzMod',
    slug: 'mod',
    domain: 'mod.fanz.website',
    port: 3153,
    logoUrl: '/platforms/mod-logo.png',
    primaryColor: '#ef4444',
    secondaryColor: '#dc2626',
    accentColor: '#f87171',
    backgroundColor: '#18181b',
    description: 'Moderation Dashboard',
    tagline: 'Keep It Safe',
    category: 'support',
    status: 'active',
    isUserFacing: false,
    requiresAuth: true,
    ssoEnabled: true,
    platformId: 'fanzmod',
    dbName: 'fanz_core',
    lastAuditDate: '2025-12-28',
  },
];

// ============================================
// HELPER FUNCTIONS
// ============================================

export function getAllPlatforms(): FanzPlatform[] {
  return [
    ...FAN_PLATFORMS,
    ...INFRASTRUCTURE_SERVICES,
    ...AUXILIARY_SERVICES,
    ...AI_SERVICES,
    ...SUPPORT_SERVICES,
  ];
}

export function getActivePlatforms(): FanzPlatform[] {
  return getAllPlatforms().filter(p => p.status === 'active');
}

export function getPendingAuditPlatforms(): FanzPlatform[] {
  return getAllPlatforms().filter(p => p.status === 'pending_audit');
}

export function getUserFacingPlatforms(): FanzPlatform[] {
  return getAllPlatforms().filter(p => p.isUserFacing);
}

export function getPlatformById(id: string): FanzPlatform | undefined {
  return getAllPlatforms().find(p => p.id === id);
}

export function getPlatformByDomain(domain: string): FanzPlatform | undefined {
  return getAllPlatforms().find(p =>
    domain.includes(p.domain) || domain.includes(p.slug)
  );
}

export function getPlatformsByCategory(category: PlatformCategory): FanzPlatform[] {
  return getAllPlatforms().filter(p => p.category === category);
}

export function getDropdownPlatforms(): {
  fanPlatforms: FanzPlatform[];
  infrastructure: FanzPlatform[];
  auxiliary: FanzPlatform[];
  aiBots: FanzPlatform[];
  support: FanzPlatform[];
} {
  const userFacing = getUserFacingPlatforms();
  return {
    fanPlatforms: userFacing.filter(p => p.category === 'fan_platform'),
    infrastructure: userFacing.filter(p => p.category === 'infrastructure'),
    auxiliary: userFacing.filter(p => p.category === 'auxiliary'),
    aiBots: userFacing.filter(p => p.category === 'ai_bot'),
    support: userFacing.filter(p => p.category === 'support'),
  };
}

// Platform-specific theme getter
export function getPlatformTheme(platformId: string) {
  const platform = getPlatformById(platformId);
  if (!platform) return null;

  return {
    primary: platform.primaryColor,
    secondary: platform.secondaryColor,
    accent: platform.accentColor,
    background: platform.backgroundColor,
  };
}

export default {
  FAN_PLATFORMS,
  INFRASTRUCTURE_SERVICES,
  AUXILIARY_SERVICES,
  AI_SERVICES,
  SUPPORT_SERVICES,
  getAllPlatforms,
  getActivePlatforms,
  getPendingAuditPlatforms,
  getUserFacingPlatforms,
  getPlatformById,
  getPlatformByDomain,
  getPlatformsByCategory,
  getDropdownPlatforms,
  getPlatformTheme,
};
